### ISSUE TITLE
some warning and error when start

### ISSUE THREAD

**Issue by zhi3210happy** [yucccc/node-api#2]
npm run initData
(node:9100) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:9100) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html

npm start
数据库连接失败：Error: Trying to open unclosed connection.
(node:3360) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
数据库连接成功

**Comment by yucccc** [comment]
This may be the reason for the mongoose APi changes, ``npm run initData``    see database is data can be out of the terminal, keep the ``npm run start``

**Comment by yucccc** [comment]
This problem has been solved. because of the mongoose version of > = 4.11.0

**Comment by SummerGC** [comment]
这个本地的数据代理我应该怎么使用阿
